# Gitleaks configuration
# https://github.com/gitleaks/gitleaks

title = "TimeTracker Gitleaks Configuration"

[extend]
# Use default rules
useDefault = true

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|api[_-]?secret)(['\"]?\s*[:=]\s*['\"]?)([a-zA-Z0-9]{32,})'''
tags = ["api", "key"]

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{24}'''
tags = ["slack", "token"]

[[rules]]
id = "stripe-api-key"
description = "Stripe API Key"
regex = '''sk_live_[0-9a-zA-Z]{24,}'''
tags = ["stripe", "api-key"]

[[rules]]
id = "stripe-restricted-api-key"
description = "Stripe Restricted API Key"
regex = '''rk_live_[0-9a-zA-Z]{24,}'''
tags = ["stripe", "api-key"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "access-key"]

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["github", "token"]

[allowlist]
description = "Allowlist for false positives"
paths = [
    '''^\.env\.example$''',
    '''^env\.example$''',
    '''\.md$''',  # Markdown files (documentation)
]

regexes = [
    '''your-secret-key-here''',
    '''your-api-key-here''',
    '''example-secret''',
    '''test-secret-key''',
    '''dummy-key''',
]

