name: Build and Publish TimeTracker Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: drytrix/timetracker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: amd64
            platform: linux/amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create simple Dockerfile
        run: |
          cat > Dockerfile.simple << 'EOF'
          FROM python:3.11-slim
          WORKDIR /app
          COPY requirements.txt .
          RUN pip install --no-cache-dir -r requirements.txt
          COPY . .
          EXPOSE 8080
          CMD ["python", "app.py"]
          EOF
          
          echo "--- Created Dockerfile.simple ---"
          cat Dockerfile.simple

      - name: Build and push Docker image
        run: |
          # Build the image using our created Dockerfile
          docker build -f Dockerfile.simple -t ghcr.io/drytrix/timetracker:main .
          
          # Push if not a PR
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker push ghcr.io/drytrix/timetracker:main
          fi

  # Multi-platform manifest job
  manifest:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}



      - name: Create and push manifest
        run: |
          # Create a simple Dockerfile for this job
          cat > Dockerfile.simple << 'EOF'
          FROM python:3.11-slim
          WORKDIR /app
          COPY requirements.txt .
          RUN pip install --no-cache-dir -r requirements.txt
          COPY . .
          EXPOSE 8080
          CMD ["python", "app.py"]
          EOF
          
          # Build and push with latest tag
          docker build -f Dockerfile.simple -t ghcr.io/drytrix/timetracker:latest .
          docker push ghcr.io/drytrix/timetracker:latest
